### ISSUE TITLE
Engineer custom turret issues

### ISSUE THREAD

**Issue by ThyHeroBro** [Mantibro/ShamanMod#2]
When this mod is active and using another mod that adds custom buildables for engineer, any skin other than default will cause the buildable to be unable to place and instead spam the left side of the screen with fake ally healthbars.
also messes with changing the abilities for engineer as they kind of freeze
This happens with the chaoticskills mod by pseudopulse but it could be with other mods

**Comment by M0ltenM3tal** [comment]
I had it to where engineer couldn't even spawn his normal turrets when playing with the shaman. figured that out in multiplayer.

**Comment by Jalswim** [comment]
This is happening to me as well but I don't have custom engineer turret mods.

**Comment by Mantibro** [comment]
fixed thanks to TheTimesweeper
